### ISSUE TITLE
Single Survey Correction feature

### ISSUE THREAD

**Issue by nspool** [aodn/nrmn-application#1084]
## Description
Apply reference data, survey completness and observation range validations. 
Add an additional "Survey Does Not Exist" validation when Site/Date/Depth does not match existing survey ID.
Also support exporting from the grid in an ingestable format, and adding an arbitary number of blank rows into the grid.

## Backlog Items

1. https://github.com/aodn/backlog/issues/4135
2. https://github.com/aodn/backlog/issues/4138

**Comment by LizziOh** [comment]
I attempted to correct survey 6002304 today however some of the metadata did not load, eg. lat, long, visibity etc.  Survey method 13 also loaded for the last row (survey not done observation).
The missing latitude and longitude created a blocking warning

**Comment by bpasquer** [comment]
The ref data was pulled out of the `survey` table, where no latitude and longitude were stored due to the coordinate being identical to the site coordinates. What should happen is that survey coordinates get pulled out of  `site_ref`  when no  coordinate information is stored at survey level.
Nathan has fixed it, ready to be tested in Systest. 

Visibility is not recorded for this particular survey according to the database.

Nathan is going to open a new issue to remove the M13 data from the correction job

**Comment by LizziOh** [comment]
Wonderful, thank you.  Also the observations seem to be split into different rows for each size category.. creating duplicate row warnings.

**Comment by LizziOh** [comment]
Also the filtering in the staged jobs is currently bugging in systest (fine in prod).  Once some things are filtered for others become available and the check boxes disappear and reset filter does not work. Curious as it is behaving correctly for the survey corrections pages.

**Comment by nspool** [comment]
Just updated SysTest to version 11.0 (690). The following fixes are ready for testing:
 - Hide any M6 and M13 observations in the corrections sheet.
 - Show all of the observations into the same row. This should fix the duplicate row warnings.
 - Fix the column filters when editing the ingest sheet.
 - Add a Total column has been added to the corrections sheet.

Please make a note if these issues are resolved or still persisting.

Trying to correct a survey that has a PQ score attached will fail with an Error 400. I've made an issue to resolve this in the upcoming iteration.

**Comment by LizziOh** [comment]
Thank you.  I can confirm that:

- all observations appear in the same row, fixing the duplicate warnings
- column filters are working as per previous versions

- the total column appears in the single survey corrections feature, however there are discrepancies.  I've tried to use the single survey correction feature on survey 923400070, and the multiple survey feature on the ingested data containing this survey (job 6). Upon validation there is a warning with the total column (47) mismatching the calculated total for Cenolia trichoptera. The values in the columns indeed do not sum to 47, however oddly they are different for the survey appearing in the single survey and the multiple survey correction feature.  On inspection of the ingested data sheet accessed from the job page both are incorrect and the true total is 47.  It appears to be an error in how the row observations are summed into one row in the new correction pages when there is a true duplicate in the ingest sheet.  
- 
![image](https://user-images.githubusercontent.com/52521522/198913026-6400b5c2-c6a7-4df8-956b-aecfdc3982ed.png)

**Comment by LizziOh** [comment]
I would also like to confirm which table about the method 6 and 13 exclusion refers to.  Do these refer to the method codes in the method_ref table? ie. 6= rugosity and 13 = PQ scores?  If so I'm confused about how this removes the "survey not done".  Or is this referring to the observable item type 6 which is "Absence", but in this case I'm confused about what then is M13?  (Basically I would like to know what M6 and M13 refers to.)

My last question on this issue is if we correct an RLS survey which had a "survey not done" observation, does that disappear when the correction is submitted and the observations are effectively re-ingested without this row, or does it get re-attached to the survey?

**Comment by LizziOh** [comment]
Deleted row reference always refers to "row 0" instead of the actual row number deleted.

**Comment by nspool** [comment]
Looking at `Cenolia trichoptera` it was ingested with two identical rows with different values in the same size class, but the same method and block. The correction sheet is only getting one of those values, which is why it's wrong but the total is correct.

Instead of displaying different rows for `10` and `27` and showing a duplicate validation warning we can sum the values of the same size class. In this case `Cenolia trichoptera` should display as a single row with values 10 and 37 in measurement columns 5 and 6. Would this be OK?

**Comment by LizziOh** [comment]
Yes, summing the values into one row with 10 and 37 summing to the total 47 would be great -  as this is how it is displayed in the endpoints where people often detect and reports errors from.

**Comment by bpasquer** [comment]
> I would also like to confirm which table about the method 6 and 13 exclusion refers to. Do these refer to the method codes in the method_ref table? ie. 6= rugosity and 13 = PQ scores? If so I'm confused about how this removes the "survey not done". Or is this referring to the observable item type 6 which is "Absence", but in this case I'm confused about what then is M13? (Basically I would like to know what M6 and M13 refers to.)

M6 is rugosity and M13 PQscore 
The "survey not done" row was generated because no M13 value where found in the observation table(they're stored in the pq_score table)

**Comment by nspool** [comment]
SND observations such as in survey 923400915 will still appear and be corrected as usual.

**Comment by LizziOh** [comment]
Ah yes thank you for the clarification - this makes sense now.

**Comment by nspool** [comment]
Just updated SysTest to version 11.0 (692). The following fixes are ready for testing:

 - Total and measurement values should now be consistent and like measurements should be summed into the same row
 - Columns should no longer be able to be dragged away and disappear

Please make a note if these issues are resolved or still persisting.

**Comment by LizziOh** [comment]
> Just updated SysTest to version 11.0 (692). The following fixes are ready for testing:
> 
> * Total and measurement values should now be consistent and like measurements should be summed into the same row
> * Columns should no longer be able to be dragged away and disappear
> 
> Please make a note if these issues are resolved or still persisting.

Thank you, I've tested these and they are resolved

**Comment by LizziOh** [comment]
I've tested a few more corrections.  Amending species, addling/cloning rows and changing observation numbers is working well.
The only thing that came up was that RLS method 12 loads as M12, but then throws a blocking error (RLS method must be 0,1,2 or 10).  This is because it usually gets ingested under method code 2.   I assume the work around is taht we change the method code back to 2 before submitting the corrections - else the UI loads them as method 2 initially.

**Comment by nspool** [comment]
> I assume the work around is taht we change the method code back to 2 before submitting the corrections - else the UI loads them as method 2 initially.
> A similar small issue is that Survey not done loads with no diver, throwing a blocking warning. so a dummy diver has to be entered before passing validations.

Yes that's right. Since the correction sheet loads the database values and uses the same validations as ingest, M12 and SND rows will need be changed to match what is expected for an ingest sheet.

**Comment by LizziOh** [comment]
It's looking great. 
One more feedback - In the survey information edit page there is now a "correct survey" button next to the delete survey button which links to this single survey (data) correction feature.  This may provide some confusion between the new button and the existing "save survey" button at the bottom.  When editing the survey information (eg. depth or site) from this page you have often to scroll down to see the "save survey" button, which is the one to use ("correct survey" takes you to the page for correcting survey observations, not the higher level metadata such as site/date/depth).  Perhaps it would be better to rename the "save survey" button as either "save survey information" or "save survey metadata" or "save survey reference data" and put it somewhere more or equally prominent than the "correct survey" link.  I think the delete survey button is better suited next to the "save survey metadata" button as it refers to the higher level changes achieved directly from this page rather than linking to the survey data/observations corrections page.
