### ISSUE TITLE
AODN portal - update metadata

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#1314]
In the metadata for the NRMN layers on the AODN portal, the ATRC website needs updating.  It is now https://atrc.au/.
Secondly, was the QAQC document supplied to IMOS last year planned to be available on the portal for public to access and for people to cite?

**Comment by bpasquer** [comment]
@LizziOh will ask Natalia @atkinsn to update the link in the metadata record. 

Is the QAQC manual you're referring to this one? 
https://content.aodn.org.au/Documents/IMOS/Facilities/autonomous_underwater_vehicles/ATRC_Methods_Manual_2022.pdf

**Comment by LizziOh** [comment]
> Is the QAQC manual you're referring to this one?
> https://content.aodn.org.au/Documents/IMOS/Facilities/autonomous_underwater_vehicles/ATRC_Methods_Manual_2022.pdf

No, it was a general NRMN one that was part of our requirements to IMOS, but its missing from the portal metadata, I think this is the final version, but unsure if any edits happens on the IMOS:
[NRMN QAQC_FINAL_v1.3.pdf](https://github.com/aodn/nrmn-application/files/12509434/NRMN.QAQC_FINAL_v1.3.pdf)

**Comment by bpasquer** [comment]
OK I will follow that up with Nat when she comes back from leave

**Comment by atkinsn** [comment]
Updated ATRC website URL on all metadata

**Comment by atkinsn** [comment]
@LizziOh I was provided with v1.2 of the QA/QC manual via the IMOS Science Officer last November. I was waiting on her to follow up on some questions, but hadn't heard from her.
So with the provision of the "final" document from you, I have put aside some time in a couple of weeks to do the work on this. I have a couple of questions for you (and Toni?) beforehand.

- Do you want a DOI assigned to this manual?
  - if so I would create a landing page for this which would be a metadata record in our catalogue, so would be found alongside the data collection metadata records.
  - we would need to add a suggested citation to the manual which would include the DOI
  - I can assist with creating this
- we would plan to host it at the same location as the ATRC manual - https://content.aodn.org.au/?prefix=Documents/IMOS/Facilities/autonomous_underwater_vehicles/
- we would also add links to this manual to relevant IMOS webpages and the other metadata records (and therefore then available from the Portal)
- Lastly, we would look at submitting it to the IMOS Community Practices on the Ocean Best Practices Repository - https://repository.oceanbestpractices.org/handle/11329/556

**Comment by LizziOh** [comment]
> So with the provision of the "final" document from you, I have put aside some time in a couple of weeks to do the work on this. I have a couple of questions for you (and Toni?) beforehand.

Thank you @atkinsn :),  Toni is away at the moment, but we get this sorted in her absence.

> Do you want a DOI assigned to this manual?
> * if so I would create a landing page for this which would be a metadata record in our catalogue, so would be found alongside the data collection metadata records.
> * we would need to add a suggested citation to the manual which would include the DOI
> * I can assist with creating this

Yes, I think this would be a good idea.  The citation should include:

Authors:  Cooper, Antonia and Oh, Elizabeth
Title: NRMN Database QA/QC Protocols
Year: 2022
Affiliation: Integrated Marine Observing System, Hobart and Institute of Marine and Antarctic Studies, Hobart


> * we would plan to host it at the same location as the ATRC manual - https://content.aodn.org.au/?prefix=Documents/IMOS/Facilities/autonomous_underwater_vehicles/

Yes, that sounds like a good place to host the document

> * we would also add links to this manual to relevant IMOS webpages and the other metadata records (and therefore then available from the Portal)
> * Lastly, we would look at submitting it to the IMOS Community Practices on the Ocean Best Practices Repository - https://repository.oceanbestpractices.org/handle/11329/556

We're happy for both those things to happen.

**Comment by LizziOh** [comment]
Further to the last comment.  I've just managed to catch up with Rick about this - the only question he had was : if we create a DOI and then later want to edit the document do we have to go through a tricky process of creating another DOI for each version?

**Comment by atkinsn** [comment]
> Further to the last comment. I've just managed to catch up with Rick about this - the only question he had was : if we create a DOI and then later want to edit the document do we have to go through a tricky process of creating another DOI for each version?

Hey @LizziOh our approach in regards to DOIs with documents is to only assign 1. So if edits are required to the document, we will then save this as a new version (with the version number forming part of the citation, alongside the DOI). 
What we will do is keep all versions of the document from our online storage, and links to each version from the landing page of the DOI (the metadata record). 
If you think there might be a regular series of edits, we can always label the most recent version as "latest" and provide this link from the collection metadata records - I can demo what I mean by this, if you think this would be useful.

**Comment by LizziOh** [comment]
Thanks @atkinsn ,  that sounds like a good solution,  I don't think this document would be edited frequently.  It sounds like you can proceed with the plan and let me know if you have any questions.
On reflection we should probably expand the abbreviations in the document title:
"National Reef Monitoring Network database quality assurance and quality control protocols"

**Comment by atkinsn** [comment]
Hey @LizziOh got a couple of things to check with you.

- here is the draft landing page of the DOI: https://catalogue-rc.aodn.org.au/geonetwork/srv/eng/catalog.search#/metadata/bc8987aa-43ac-46a9-b5cf-de0cd4c097b8/formatters/xsl-view?root=div&view=advanced
  - Point of contact, I have us and Toni, do you want me to add you as well?
  - With the links 
     - is it relevant to this document to have the RLS and ATRC websites?
     - is it relevant to this document to have the links to the RLS and ATRC methods manuals?
  - You can see the suggested citation I have at the bottom of the metadata record. As I have expanded the abbreviation in the title of the metadata record, I am happy if the abbreviation is used in the citation, which matches the document, and having the DOI there means that users would have access to that full title anyways. Thoughts?


In regards to the document itself
- When we go to upload the document to our online storage, I will remove 'final' from the filename.
- As I suspect that this version 1.3 has been used for awhile. The process of adding a DOI to this document and a suggested citation, should trigger a new version, I suggest 1.4. 
  - I think the version number should be added to the title page, perhaps with a month, year or just year?
- I think the logical place to have a suggested citation is pg 15 with a new title: 'Contact information and Citation'
   - I would add this page to the Index on pg 2
   - I have changed the date from 2022 to 2023 due to the version number increase
   - The citation normally just includes the "publisher", which is this case would be IMOS (so haven't included IMAS)
   - Citation: ""Cooper, A. and Oh, E. (2023). NRMN Database QA/QC Protocols Manual. Version 1.4. Reef Life Survey; Integrated Marine Observing System. DOI: 10.26198/vj3w-d037 (https://doi.org/10.26198/vj3w-d037)."  This may evolve based on your thoughts above.

**Comment by atkinsn** [comment]
Hey @LizziOh 
- I have finalised and published the metadata record
- I have published the DOI
- the file is available here: https://content.aodn.org.au/?prefix=Documents/IMOS/Facilities/autonomous_underwater_vehicles/
- I have asked for a link to the document to be added to the IMOS website (https://imos.org.au/auv/national-reef-monitoring-network)

**Comment by atkinsn** [comment]
@LizziOh which of the Portal collection metadata records would you like this report added to? 
- specific ones,
- or all of them?

**Comment by LizziOh** [comment]
Thanks @atkinsn !
The document is relevant to all of the Portal collections and their associated metadata records.

**Comment by atkinsn** [comment]
All finalised and submitted to Ocean Best Practice 
[https://repository.oceanbestpractices.org/handle/11329/2379](https://protect-au.mimecast.com/s/-qbcCQnzVqtkjwQJ1sP-Ygn?domain=repository.oceanbestpractices.org)
