### ISSUE TITLE
Ability to edit Survey reference information

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#323]
v0.0190
Currently, the only things you can edit are notes, project, and marine park /status.  
However need to edit depth, time, site (from drop down of existing sites), date, diver (from drop down list), buddy (from drop down list), PQs diver (from drop down list), direction, program (from drop down list) etc etc.  
Only surveyID should be blocked from editing. 
ADDITIONAL NOTE:  Changing these is necessary especially whilst without a corrections mechanism.  However, necessary validation checks should be inbuilt to any changes in the edit survey mode.  These include
 date validations (format, no future dates or before 2006), 
Site code and site name exist (and match if both editable). 
Time incorrect format.  
Direction validations. 
 etc...

</google-sheets-html-origin>

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3124)

**Comment by LizziOh** [comment]
also need to view and edit site code, although this needs to match the site name, lat and long in the survey edit feature

**Comment by ccmoloney** [comment]
Some selected fields will be editable:
- Site Code
- Depth

Need to understand the validation we need to implement.

**Comment by LizziOh** [comment]
Validations:  that the site-code is valid and matches the site name from the sites list (NOTE: we will need to edit site name too for this to be useful).  That the new combination of date/depth/site does not match any other existing survey (NOTE: the depth alluded to here is the decimal depth - ie. the combination of the integer depth and survey number stored in the db tables).

**Comment by APaulic** [comment]
> also need to view and edit site code, although this needs to match the site name, lat and long in the survey edit feature

@LizziOh in the above line you mention that the lat and long of the survey need to match the site. What margin of error should I use here as there are no, or very minimal, perfect matches between surveys coordinates and the coordinates of the site in the database.

**Comment by LizziOh** [comment]
True. I forget that some RLS surveys have a survey lat/long that differs from the site's lat/long. The margin for this is actually about 200m. If it is more that that it should be added as a new or different site.

**Comment by LizziOh** [comment]
Please also note that there is no point allowing the editing of a site code without the ability to edit site name.  In the case that a survey is incorrectly loaded with the wrong site code then the wrong site name will be ingested too (as it is assigned based on site code ingested not the site name column of the staged data). Both need to be corrected, which in this case means the lat/long can be prefilled based on the new site code entered.

**Comment by APaulic** [comment]
Just to clarify @LizziOh, I have listed the fields and their controls below. The idea of editing a site name and choosing site codes sounds a little scary to me just because there is potential to duplicate site names with different site codes if someone was to select a different site code but not update the name. The below is how I envision the form controls will look, can you please confirm that this is what you are expecting?

### Included Fields
- surveyId
   - Field: Text
   - Editable: No 
- siteName
   - Field: Free text
   - Editable: Yes 
- siteCode
   - Field: Dropdown
   - Editable: Selectable - No free text option
- program
   - Field: Dropdown
   - Editable: Selectable - No free text option
- surveyDate
   - Field: Free text
   - Editable: Yes 
   - Validation:
      - Must not be in future
      - Must be after 2006-01-01
      - Date format must be yyyy-mm-dd
- surveyTime
   - Field: Free text
   - Editable: Yes 
   - Validation:
      - Date format must be hh:mm:ss
- depth
   - Field: Free text
   - Editable: Yes 
- surveyNum
   - Field: Free text
   - Editable: Yes 
- visibility
   - Field: Free text
   - Editable: Yes 
- direction
   - Field: Free text
   - Editable: Yes 
   - Validation:
      - Must be one of [N, S, W, E, NE, SE, SW, NW, NNE, ENE, ESE, SSE, SSW, WSW, WNW, NNW]
- longitude
   - Field: Free text
   - Editable: Yes 
   - Validation:
      - Must be between -180 and 180
      - Must be within 200m of site
- latitude
   - Field: Free text
   - Editable: Yes 
   - Validation:
      - Must be between -90 and 90
      - Must be within 200m of site
- protectionStatus
   - Field: Free text
   - Editable: Yes 
- insideMarinePark
   - Field: Dropdown
   - Editable: Selectable - No free text option
- notes
   - Field: Free text
   - Editable: Yes 
- pqDiver
   - Field: Dropdown
   - Editable: Selectable - No free text option
- blockAbundanceSimulated
   - Field: Tick box
   - Editable: Boolean 
- projectTitle
   - Field: Free text
   - Editable: Yes 

#### Additional Validations:
- Combination of date/depth/site.surveyNum does not match any other existing survey

### Fields Not Included
- method
- block
- pqCatalogued
- pqZipUrl
- pqDiverInitials
- surveyNotDone

Please let me know if you are expecting to see any of the fields not included. I have left them off the form as they are complex or controlled by the system/scheduled tasks.

**Comment by LizziOh** [comment]
I've tried multiple times to change depth and the site code (with matching changed site name, lat and long) but it will not save and returns error 400.

**Comment by bpasquer** [comment]
@LizziOh  I think it's been fixed , can we close this issue?
