### ISSUE TITLE
Size class checks (L5,L95,Lmax) errors

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#350]
- checks compare reference values with the size value shifted by one class up  for example:
 For a value of in the size column 7.5 cm, a warning is reported: `Measure 10: value is outside  l5/l95[2.5-7.5]` -> 7.5cm is considered as 10cm

- checks should validate values equal to the lower or upper bounds of the valid range, for example: 
`Measure 10: value is outside  l5/l95[2.5-10]`->   10 cm is in the valid range and should be accepted 

-checks should accept valid values!
currently reporting: `Measure 5: value is outside  l5/l95[2.5-12.5]` -> 5cm is well within the valid range.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3083)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
As discussed in meeting 8/6/21, display of the L5/95 error warnings are better grouped by species and row, rather than column.  The errors were also sometimes inconsistent within each row, for example an error that pointed to a row with Heliocidaris in size 10 said: Warning Measure: 10 is outside l5/95 [0.0,4.5]. indicating that L95 is 4.5, however there was a sighting at 7.5 in that same row and it does not have a warning.  Also need to check Lmax logic as it seemed an Lmax of 7cm did not trigger a warning when the 7.5cm size class contained an observation.

**Comment by bpasquer** [comment]
Note that a lot of warnings raised in the feedback are not highlighted in orange(for ex the Heliocidaris example above)
Is the test to trigger the message and the color coding different?

**Comment by LizziOh** [comment]
tested
