### ISSUE TITLE
Add/Edit Site should warn if a new site to be created that is too close to an existing site

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#369]
Software Version: v0.0.234

There is currently no check in Add Site to warn or block a user from creating a site that is geographically close to an existing site.

The system should either wanr a user that there is a site nearby - or block them from adding a site that is within a defined distance (200m?) of an existing one.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3120)

**Comment by APaulic** [comment]
Currently, 316 (7.7% of all sites) are within 200m of another site. Below is the query I used to obtain the results and a CSV of the results. 

Note: This does not list the same overlap twice. i.e. if A and B are within 200m then they are only listed once instead of stating that A is within 200m of B and B is within 200m of A.

Query:
```sql
--SELECT COUNT(*) FROM (
SELECT 
	src.site_id AS source_id, 
	src.site_name AS source_site, 
	other_site.site_id AS site_too_close_id, 
	other_site.site_name AS site_too_close_name, 
	ROUND(CAST(ST_Distance(CAST(st_makepoint(src.longitude, src.latitude) AS geography), CAST(st_makepoint(other_site.longitude, other_site.latitude) AS geography)) AS NUMERIC), 2) AS distance 
FROM site_ref src 
INNER JOIN site_ref other_site ON (src.site_id < other_site.site_id AND ST_Distance(CAST(st_makepoint(src.longitude, src.latitude) AS geography), CAST(st_makepoint(other_site.longitude, other_site.latitude) AS geography)) < 200)
ORDER BY src.site_id, other_site.site_id 
--) dat
```
CSV:
[Sites Within 200m.csv.txt](https://github.com/aodn/nrmn-application/files/6952123/Sites.Within.200m.csv.txt)

**Comment by LizziOh** [comment]
Can this be a warning instead of a blocking feature?  A lot of these sites are legitimately distinct, because the 200m rule is not all encompassing.  When creating a new site topography and natural barriers are taken into account.  For example 2 reefs separated by a large sand patch, or two reefs on either side of a point can be distinct sites.  If the system flags the 200m rule as a warning pop up window which you have to accept it would be a good prompt to then investigate the new site on google earth or email the diver and ask if it was distinct.

Thank you for running this query though, it will come in handy reviewing some of these sites in question perhaps.  :)

**Comment by bpasquer** [comment]
could be a warning when creatin a new site
