### ISSUE TITLE
New surveys should inherit marine park status from the site

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#401]
Survey  attributes 'Protection status' and  'Inside Marine Park' should be inherited from the site

**Comment by bpasquer** [comment]
See https://github.com/aodn/backlog/issues/3186

**Comment by LizziOh** [comment]
tested, this is now working.

There still is very inconsistent entries for exisitng data.  Eg.  MIR-S1 has prtection status of "reserve", "NULL", and "No take".  The site metadata states that the site has been No take since 1991 (before the our first survey in 1992).  This may be a bulk correction task to add to the maintenance list in either nrmn-application or lodge in NRMN repo @bpasquer ?

**Comment by bpasquer** [comment]
would be best to open that issue in the NRMN repo. If /when I need developers, I will create a  internal (Backlog) task
