### ISSUE TITLE
Blank lines being staged

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#506]
Some files have lots of lines which do not contain data, but are being staged because there is 'something' in the rows.

The system previously used the presence of a value in the ID column as an indicator that the row did, indeed, contain data.

We changed this to detect whether a row had a value in any column because some files coming in were missing ID values for some rows & therefore we weren't staging all the rows.

## Tasks
- [ ] Revert to using an ID value as the indicator of a row which has data.
- [ ] Report in the job log if we skip any rows that are missing an ID value but have values in any of the known columns
- [ ] DOD

**Comment by ccmoloney** [comment]
@atcooper1 @LizziOh Are you happy for us to go back to requiring each row of valid data to have an ID value?  You will have to check before submitting sheets.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3330)

**Comment by LizziOh** [comment]
I don't think it is a good idea to eliminate rows without an ID value.  It seems risky, particularly because many spreadsheets have been combined from different diver's own files... and it would be easy for the ID columns to be jumbled or missing.

**Comment by ccmoloney** [comment]
@LizziOh We don't know at this point how the RLS tool did it...  How do we detect which rows are valid and which are to be skipped/discarded?

**Comment by ccmoloney** [comment]
The actual value of the ID cell for the row doesn't matter to us (it isn't even staged) - but we can use it as an indicator that it is a valid row

**Comment by atcooper1** [comment]
To help explain how the existing RLS tool runs and deals with this: The tool stops when it finds duplicated rows. The user can then see the row where the tool stops and can decide whether this is the true end of the sheet (i.e. the tool has appropriately cut off the excess, duplicated rows) or whether the tool has prematurely stopped because the diver has made an error with block/method entry. Once the block/method/depth errors have been corrected, the tool will run to the end of the sheet and cut off excess rows (by identifying them as duplicates), or stops when it finds blanks rows.  This is one of the first validations to run in the existing tool as it affects data structure/total rows ingested etc. 

Perhaps a work-around would be for the user to delete a row of duplicated data at the end of the sheet after ingest so the UI can find the true end of the sheet? That way, any duplicated rows after a blank row are ignored? Could that work? So the current UI validation check would stay the same (and still highlight the excess rows at the end)  to help flag to the user that they need to  manually clear the contents of a row to help identify the end of the sheet?

**Comment by ccmoloney** [comment]
@LizziOh @atcooper1 Could you send me a sheet that shows what kind of blank/junk rows we are talking about?

**Comment by ccmoloney** [comment]
@atcooper1 @LizziOh 

SO: what is the rule?  Something like:

If we see 3 duplicate rows with Total = 0, then that signals the end of the data?

**Comment by atcooper1** [comment]
Yes, that could work.... only thing to consider is that if a sheet finishes with Debris zero, Survey not done, or No Species Found, the total =0 and this is a valid final row (therefore finding three duplicates with total = 0 in a row will include a row of valid data, so will need to cut the second row). But if a sheet finishes with a species, the last row of data will have a Total ≥1. (i.e. the first row of three duplicate rows where total = 0 is the row to cut).

**Comment by LizziOh** [comment]
well I guess if the UI check for a duplicate row for every field it should be okay (3 duplicate rows with Total = 0, signals the end of the data) because technically for vaild entries of the Debris Zero, SND and NSP one field should change (depth, and/or block)?

**Comment by ccmoloney** [comment]
From Toni:

Hi Cam,

> Re: cutting the datasheets, I thought I’d try and explain my terribly worded comment with an example of the two different scenarios where data finishes with a true zero or a species! I’ve highlighted the last rows of valid data in 2 examples.
> 
> For sheets that end with Survey not done, Debris Zeros and No species found: if the UI finds 3 rows of duplications (total = 0), the first row (highlighted) is in fact a valid row of data so the UI should cut the SECOND duplicated record:

![image](https://user-images.githubusercontent.com/30034813/128451682-07981fb2-f31d-4d15-9fec-d368186e5509.png)

> Whereas if a sheet finishes on a species, then the FIRST duplicated row (where total =0) should be cut (i.e. the row below the highlight):

![image](https://user-images.githubusercontent.com/30034813/128451728-908a26a5-9a30-4bfa-a9f9-3b45bec77a6a.png)

> Cheers,
>
> Toni

**Comment by ccmoloney** [comment]
A related issue raised as https://github.com/aodn/nrmn-application/issues/519

**Comment by bpasquer** [comment]
Update : The duplicate row rule now applies to 'Debris Zero' , 'Survey Not done' and 'No species found'

**Comment by LizziOh** [comment]
This is working for sheets that I have tested
