### ISSUE TITLE
All geoserver layers are capped at 50 rows on download

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#649]
All Geoserver downloads are only downloading the first 50 rows of data.

**Comment by bpasquer** [comment]
Aouple of comments after investigating it further today:
- NRMN datasets are downloadable in full from the AODN portal. 
- by defaults all request for CSV download submitted to geoserver-123.aodn.org.au (the production geoserver behind the portal) are capped at 50 rows (irrespective of the layer). The code that is behind the limit "&maxFeatures=50"  is visible in the url of the request in the screenshot below:  
![Screenshot from 2021-11-25 14-39-30](https://user-images.githubusercontent.com/3733612/143375792-89454c73-a29a-4e20-ad98-59162a0deedd.png)
A workaround to directly request a dataset in full from geoserver-123 is to remove that "&maxFeatures=50". 
If you want to downlaod  in CSV  add "&outputFormat=csv" at the end of the URL:
http://geoserver-rc.aodn.org.au/geoserver/imos/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=imos%3Aep_m0_off_transect_sighting_public_data&outputFormat=csv


Now, since the AODN portal is our preferred access point to the NRMN data collections and the one that will be publicized, is the  maximum row limit still a issue?
