### ISSUE TITLE
Update of M2 cryptic fish and inverts endpoints

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#697]
### Cryptic fish ###
An update of the private and public endpoint and method-species rule is required in order to :

- [x] exclude non cryptic fish from ep_m2_cryptic using the info from the method_species table instead of the method  an observation has been collected with https://github.com/aodn/nrmn-application/issues/695
- [x] add "Unidentified cryptic fish” and “Unidentified fish (cryptic)”  to the list of M2  Cryptic species in the method_species table
- [x] add Hexagrammidae  to the list of M2 Cryptic species in the method_species table https://github.com/aodn/nrmn-application/issues/659

### Inverts ###
(from info Toni's email 2021-11-08) 
An update of the  private and public endpoints in order to ADD the following taxonomic groups :
CLASS Crinoidea
CLASS Holothurioidea
CLASS Pycnogonida
CLASS Cubozoa
CLASS Hydrozoa
PHYLUM Echiura
PHYLUM Ctenophora
FAMILY Pectinidae

**Comment by bpasquer** [comment]
CLASS Cubozoa and CLASS Hydrozoa are not part of the method species rule used for the checking the if a species is recorded under the right method  (and also the M2 cryptic fish endpoint now )

Should I add them to the rule?

**Comment by LizziOh** [comment]
I've tested both M2 endpoints and am happy with the changes made.  

Notes:  
I've listed the non-cryptic fish species now excluded from the ep_m2_cryptic_fish endpoint and am confirming with Rick and Gedgar whether 10 more families should be added to the cryptic fish family list (see checking attached for those 10, highlighted yellow). 3 species also appeared to have been excluded but were just recent observations for M2 only ingested in prod, not systest.  One case of an incorrectly spelt family name has been fixed in prod.

Echiura were not appearing in M2_inverts due to coding error, now being rectified, and there are no M2 cubozoan observations so these are (correctly) not in the extract.

[non-cryptic fish excluded_RSS_ESO.xlsx](https://github.com/aodn/nrmn-application/files/7600448/non-cryptic.fish.excluded_RSS_ESO.xlsx)

**Comment by LizziOh** [comment]
Attached is list of cryptic fish excluded from M2 endpoint with new rule (to include only those with family in cryptic fish family list).
There are comments of some which should be added to the cryptic fish family list and others that should be investigated as errors to correct or changed to M0 (for example the great white shark recorded as cryptic fish??)
[Cryptic fish family list review.xlsx](https://github.com/aodn/nrmn-application/files/7630713/Cryptic.fish.family.list.review.xlsx)
.
As the tasks in this issue have been addressed I will close this issue and have created another #711  to address the review of the cryptic fish family list and possible erroneous cryptic fish observations.
