### ISSUE TITLE
Missing observations from AODN geoserver layers for RLS website

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#995]
Issue relates to Data issue  #749

I noticed some issues when I changed the survey data to AODN rather than the old IMAS geoserver layers:
•	It seems like some sightings have gone missing. For example, there were multiple sightings of Gnathodentex aureolineatus at ACEH17 on 2009-02-27 in the original URL, but none in the new URL. Any idea what happened?
•	I ran into trouble parsing some of the Spanish names (full list). I worked around it by fixing them with a manual mapping, but if there's an issue with the way AODN encodes them, it'd be nice to get it fixed at the source (there were no such issues with the old server).

**Comment by atcooper1** [comment]
I have discovered this problem seems to extend beyond Gnathodentex aureolineatus, but the issue seems to be very irregular (i.e. not all records of a species are absent from NRMN M1_ep). This is not the full extent of potential discrepancies, however it is a very time consuming task to do manually, so i'm hoping there is a simple cause for this glitch in the code otherwise perhaps we can discuss a better way of checking this at our next meeting?
[M1_IMAS and ep_M1 discrepancies.xlsx](https://github.com/aodn/nrmn-application/files/8753621/M1_IMAS.and.ep_M1.discrepancies.xlsx)

**Comment by bpasquer** [comment]
These are my finding from comparing NRMN and IMAS DB:
### Species present in ep_M1 but absent from IMAS_M1
the discepancies are related to superseding:

- Oxycheilinus digrammus superseded by Oxycheilinus digramma
- Helcogramma striatum superseded by  Helcogramma striata
###  _Cheilodipterus macrodon_ and _Gnathodentex aureolineatus_ present in IMAS-M1 but absent in ep_M1(public):

Some records of _Cheilodipterus macrodon_ and _Gnathodentex aureolineatus_ are excluded  from the ep_M1_public because of the condition on "Class".
All the missing records of _Cheilodipterus macrodon_ and _Gnathodentex aureolineatus_ have a superseded name as recorded_ species_name   (_Cheilodipterus heptazona_ _Gnathodentex aurolineatus_ respectively). Both superseded species records were migrated  with empty Phylum, Class and Order. 
The taxonomy of these species haven't been updated along with the other superseded following https://github.com/aodn/nrmn-application/issues/758 because its  "family" is populated, whereas the query to identify the superseded species missing taxonomy that was testing a condition for the fileds "family" = Null.

**Comment by bpasquer** [comment]
a total of 11 M1 species are impacted by this problem and need their taxonomy to be updated:
| recorded_species_name       |
|-----------------------------|
| Cheilinus bimaculatus       |
| Cheilodipterus heptazona    |
| Taeniura lymna              |
| Aulacocephalus temmincki    |
| Scomberoides commersonianus |
| Scarus sordidus             |
| Gnathodentex aurolineatus   |
| Scarus microrhinos          |
| Centropyge eibeli           |
| Trachinotus bailloni        |
| Siganus margaritiferus      |

**Comment by bpasquer** [comment]
related to #772

**Comment by atcooper1** [comment]
Taxonomy for these species listed have now been updated/filled in the Ref data.

**Comment by bpasquer** [comment]
@atcooper1 the public endpoints will be refreshed tonight
